### ISSUE TITLE
size of texts vs size of thumbnails

### ISSUE THREAD

**Issue by yastarabe** [Siddy212/iconic-es-de#4]
Using "grid boxart" variant, on gamelist view; we need a good font size preset, to show all metadata texts in a small size and the cover images of the games in a big size.

None of the actual font size presets fits that: the smallest presets (small and medium) shows nice texts of all metadata but too little cover images, and the largest presets (large and extra large) shows nice big cover image size but too big texts and not all metadata fields.

Dear developers, please add a font size preset combining small texts and big cover images.

**Comment by Siddy212** [comment]
Hello, doesn't the Medium font size already share boxart size with the Large font size? I just tested and the only difference between these two are the amount of metadata shown.

**Comment by yastarabe** [comment]
You right, Medium size and Large size have both the same boxart size.
Medium size it's my setting for the big screen, on a Windows system, it
looks very good.
But for small devices like my android console, i think the boxart size of
Medium and Large presets it's too little, so i prefer the Extra Large
preset, with a big beautiful covers... and a too big texts.
A preset with the biggest boxart size and a small font text with all
metadata, it will be nice!
Please, dear developer!

Missatge de Siddy212 ***@***.***> del dia dt., 4 de juny 2024
a les 15:27:

**Comment by Siddy212** [comment]
I'm sorry, but I feel that this would be a very specific use case to have a new variant made. Typically users that want to have the largest boxart size would also want large font sizing as it is easiest on small devices. If it doesn't follow this method it may be very confusing for people.

**Comment by yastarabe** [comment]
ok, i understand, thanks for the chat :-)

Missatge de Siddy212 ***@***.***> del dia dt., 4 de juny 2024
a les 23:21:

**Comment by Siddy212** [comment]
No problem! If you wish to change it yourself though, you can edit the xml files I the coversize folder. Add medium to where it says x-large for your aspect ratio and you will get this look.

**Comment by yastarabe** [comment]
Thanks for the tip! i found the coversize folder, i will try tomorrow. Good
night!

Missatge de Siddy212 ***@***.***> del dia dt., 4 de juny 2024
a les 23:31:

**Comment by yastarabe** [comment]
And after fighting for a while against evil xml files, i got it! Big covers
and small metadata texts!
Thanks a lot for your wise advice, developer friend!

Missatge de Salvador Justo Roca ***@***.***> del dia dt., 4 de
juny 2024 a les 23:37:

**Comment by Siddy212** [comment]
No problem! I'm glad this worked out for you :)
