### ISSUE TITLE
Scaling box art

### ISSUE THREAD

**Issue by Bonaf1de** [Siddy212/iconic-es-de#5]
First of all: thanks for your great work!

One minor gripe, though. On soms systems, the box art is pretty small (when using the Theme Vartiant: _Grid: Boxart_). This is mostly the case with square box art (GBC, GBA, etc.).

Can you incorporate a setting to scale said box art?

**Comment by Siddy212** [comment]
Hi, glad you like the theme. This is already built in to the font size which scales boxart images. If you increase to Large/X-Large it will scale up the size.

**Comment by Bonaf1de** [comment]
Dohhhh! I missed the Extra Large setting ;) Cheers!

**Comment by Siddy212** [comment]
No problem! Glad that works for you 🙂
