### ISSUE TITLE
wrong coversize of covers on grouped custom collections

### ISSUE THREAD

**Issue by yastarabe** [Siddy212/iconic-es-de#6]
Hi, dear developer, i found a little issue:
I start to create Custom Collections. I created four, two from the iconic-es-de theme ("mario" and "completed") and two from scratch ("couch coop games" and "couch versus games")

- when i set the option "Group custom collections" to "Never", the gamelist view (grid boxart variant) of all custom collections is nice, all covers are shown with a square cover size.
- but when i set "Group custom collections" to "Allways" (which is what i prefer), the coversize changes to a wrong one, a long horizontal rectangle... good coversize for SNES games covers, but wrong for almost every other systems.

I attach two screenshots of my Mario gamelist, to see how good it looks with the "never group" option, and how bad it looks with the "allways group" option.
![group custom collections Allways](https://github.com/Siddy212/iconic-es-de/assets/145613902/3d304686-0292-4b15-b29c-44491d30d2f6)
![group custom collections Never](https://github.com/Siddy212/iconic-es-de/assets/145613902/22a1fa94-1158-41b3-ba7e-3ec2e075a512)

**Comment by Siddy212** [comment]
Thanks for catching this! I've just made a change so that custom-collections also use 1-1 aspect ratio. Try updating and let me know if that solved the issue for you.

**Comment by yastarabe** [comment]
Updated and perrrfect! squared aspect ratio on all grouped custom collections.
Bug hunter at your service, friend developer!

**Comment by Siddy212** [comment]
Great, glad it worked for you 😊
