### ISSUE TITLE
Request: add option to use title screen in text variant

### ISSUE THREAD

**Issue by valzi** [Siddy212/iconic-es-de#9]
I hate mix images, haha.

(Thanks, this is my favorite theme, mostly because of how the the metadata displays.)

**Comment by Siddy212** [comment]
Hey, glad you like the theme! If you delete the miximages it will default to the game covers instead. Would that work as a simple fix?

**Comment by valzi** [comment]
I didn't have miximages and it didn't display anything at all. I don't want
game covers either.

However, I did find a workaround! I just set the scraper to build miximages
out of title screen images only without mixing anything else in. Thanks for
responding.

**Comment by Siddy212** [comment]
Okay great, that should work then :)
